### ISSUE TITLE
Please remove fitforfun.de from adult.txt

### ISSUE THREAD

**Issue by thomasmerz** [jankais3r/Synology-Safe-Access-domain-list#1]
This is not "adult"-stuff:

> Fit for Fun war eine [Fitness](https://de.wikipedia.org/wiki/Fitness)-[Zeitschrift](https://de.wikipedia.org/wiki/Zeitschrift), die von 1994 bis 2021 monatlich erschien.

https://de.wikipedia.org/wiki/Fit_for_Fun

**Comment by jankais3r** [comment]
Hi, thank you for flagging this, but this repository only serves as a mirror of Synology's list. If you want to have this entry removed, I recommend contacting them directly.

**Comment by jankais3r** [comment]
Hi, I updated the database to the latest version, and your requested website is no longer listed in the Adult category.

**Comment by joe820912boy** [comment]
@jankais3r 

hi

the servicejeux.skyrock.com in games.txt seems be unavailable now
